// run-cycle.js — Orchestrator for the weekly AI reinvention cycle.
//
// Invoked by anthropics/claude-code-action@v1 (SHA-pinned per DC14) via the
// cron workflow (U6). The action's prompt (scripts/cycle/prompts/cycle.md)
// instructs Claude Code to run this Node script; the script marshals inputs,
// validates outputs, runs smoke gates, and writes the archive.
//
// What this script DOES NOT do:
//   - It does not call the Anthropic API directly. The Author and Editor
//     "calls" below are stub functions whose real implementation comes from
//     Claude Code's Agent tool at runtime. In production, the cycle.md
//     prompt's invocation of this script overrides the stubs by spawning
//     subagents and feeding their structured output through these stubs'
//     signatures.
//
//     This split is deliberate: the orchestrator's responsibility is to
//     assemble inputs and enforce gates; the LLM marshalling is Claude
//     Code's responsibility. Keeping them separated means the orchestrator
//     is fully unit-testable without mocking an API.
//   - It does not call git. Staging happens here (file writes); commit,
//     push, and PR open are the U6 workflow's job.
//
// CLI args:
//   --dry-run                 Use stub Author output from a fixture; write
//                              archive to /tmp/ instead of archive/YYYY-MM-DD/
//   --artifact-date YYYY-MM-DD
//                              Override the cycle date (default: today UTC)
//   --max-retries N           Author/Editor revision loop cap (default: 3)
//   --fixture-path PATH       For --dry-run, where to read the stub Author
//                              output from (default: stub fixture below)
//
// Exit codes:
//   0  Success — archive written and staged
//   1  Author/Editor revision loop exhausted retries
//   2  Schema or freeze error after all retries
//   3  Smoke or source-scan gate exhausted retries
//   4  Misconfiguration (missing configs, malformed CLI args)
//
// Final stdout line: a single JSON object the GitHub Action parses to fill
// in the PR description or failure-issue body.

const fs = require("node:fs");
const path = require("node:path");
const crypto = require("node:crypto");
const { execSync } = require("node:child_process");

const { validate: validateAuthorOutput } = require("./output-schema.js");
const { assemble: assemblePerformanceLog } = require("./performance-log.js");
const { freeze } = require("./freeze-archive.js");
const { scanArtifact } = require("./source-scan.js");

const REPO_ROOT = path.resolve(__dirname, "..", "..");

// ============================================================================
// DC10 — diversity-memory window sizes. These are named constants per the
// plan's Scope Boundaries decision: inlined here until a second consumer
// appears or the values need tuning. Promote to config/cycle-config.js when
// either happens.
// ============================================================================
const THEME_DIVERSITY_N = 8;
const TOPICAL_CLUSTERING_N = 4;
const RATING_CONTEXT_N = 12;

// ============================================================================
// DC9 — cost ceiling enforcement. The orchestrator can't see API token spend
// from inside claude-code-action; --max-turns and timeout-minutes are the
// real ceilings. These constants document the intended values for
// downstream code that surfaces them in notifications.
// ============================================================================
const MAX_TURNS = 60;
const MAX_RUN_MINUTES = 45;

// Default Author/Editor revision cap (DC18 — autonomous in the happy path,
// reactive recovery on failure). Configurable via --max-retries.
const DEFAULT_MAX_RETRIES = 3;

// ============================================================================
// U8 — inlined notification templates. Promote to scripts/cycle/notify-
// templates.js when first changed (per Scope Boundaries).
// ============================================================================

const PR_BODY_TEMPLATE = `## Drop: \${theme_name}

\${editorial_note}

### Where the facts live
- **Firm name:** \${where_firm_name}
- **Mission:** \${where_mission}
- **Portfolio:** \${where_portfolio}
- **Team:** \${where_team}
- **Contact:** \${where_contact}

### History entrance
\${history_view_concept}

### Tweet draft
\`\`\`
\${tweet_draft}
\`\`\`

### Screenshot brief
\${screenshot_brief}

---
This PR was generated by the weekly AI reinvention cycle. Once CI is green and \`main\` hasn't moved, it auto-merges.

[Live preview](\${preview_url})
`;

const SUCCESS_ISSUE_TEMPLATE = `## Drop shipped: \${cycle_date}

**Theme:** \${theme_name}
**Topical:** \${topical_hook_or_none}

\${editorial_note}

### Live drop
\${live_url}

### Press kit
**Tweet:**
\`\`\`
\${tweet_draft}
\`\`\`

**LinkedIn:**
\`\`\`
\${linkedin_draft}
\`\`\`

**Screenshot brief:** \${screenshot_brief}

### Rate this drop
Edit \`archive/\${cycle_date}/rating.json\` directly via PR, or comment with \`/rate N "note"\` if the bot is wired up.

\`\`\`json
[{"rater": "your-name", "rating": 4, "note": "what landed", "ts": "ISO8601"}]
\`\`\`
`;

const FAILURE_ISSUE_TEMPLATE = `## Cycle failed: \${cycle_date}

**Reason:** \${failure_reason}

**Retries used:** \${retries_used} / \${max_retries}

### Workflow run
\${workflow_run_url}

### Last attempt summary
\${last_attempt_summary}

### Manual rollback (if a bad drop slipped through)
\`\`\`bash
git revert <merge-sha> && git push
\`\`\`

v1 has no dedicated rollback workflow — use \`git revert\` if a bad drop slipped through and the cycle didn't catch it. This is rare; consider promoting to a workflow if it happens repeatedly.

### Next steps
- Rerun the cycle manually via \`workflow_dispatch\` on \`weekly-cycle.yml\` once the underlying issue is addressed.
- If configs need changes (brand-brief, no-fly-list, topical-rubric), edit them first — those changes land in the NEXT cycle.
- If the orchestrator itself is buggy, fix it before rerunning.
`;

// Lightweight template renderer used by both this orchestrator and the
// weekly-cycle.yml workflow. Substitutes `${key}` placeholders with values from
// the passed object; unknown keys render as `(none)` so a missing field never
// silently leaks the placeholder syntax into a user-visible issue/PR body.
function renderTemplate(template, vars = {}) {
  return template.replace(/\$\{([a-zA-Z_][a-zA-Z0-9_]*)\}/g, (_, key) => {
    const v = vars[key];
    if (v === null || v === undefined || v === "") return "(none)";
    if (Array.isArray(v)) return v.join("\n");
    return String(v);
  });
}

// ============================================================================
// CLI parsing
// ============================================================================

function parseCliArgs(argv) {
  const opts = {
    dryRun: false,
    artifactDate: null,
    maxRetries: DEFAULT_MAX_RETRIES,
    fixturePath: null,
  };
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === "--dry-run") {
      opts.dryRun = true;
    } else if (arg === "--artifact-date" && i + 1 < argv.length) {
      opts.artifactDate = argv[++i];
    } else if (arg === "--max-retries" && i + 1 < argv.length) {
      const n = parseInt(argv[++i], 10);
      if (Number.isNaN(n) || n < 0) {
        throw new Error(`--max-retries must be a non-negative integer, got: ${argv[i]}`);
      }
      opts.maxRetries = n;
    } else if (arg === "--fixture-path" && i + 1 < argv.length) {
      opts.fixturePath = argv[++i];
    } else if (arg.startsWith("--")) {
      throw new Error(`unknown CLI flag: ${arg}`);
    }
  }
  return opts;
}

function todayUtcIso() {
  const d = new Date();
  const yyyy = d.getUTCFullYear();
  const mm = String(d.getUTCMonth() + 1).padStart(2, "0");
  const dd = String(d.getUTCDate()).padStart(2, "0");
  return `${yyyy}-${mm}-${dd}`;
}

function isValidDateString(s) {
  return /^\d{4}-\d{2}-\d{2}$/.test(s);
}

function generateCspNonce() {
  // Base64-encoded 16-byte random, URL-safe so it doesn't break HTML attrs.
  return crypto.randomBytes(16).toString("base64").replace(/[+/]/g, (c) =>
    c === "+" ? "-" : "_"
  );
}

// ============================================================================
// Config reading
// ============================================================================

function readJsConfig(relativePath) {
  // The existing CLI configs (portfolio.js, team.js, etc.) assign to a top-
  // level const and only conditionally module.exports. For configs that
  // DON'T export (older ones), we evaluate them in a vm sandbox and read
  // the named global. For configs that DO export (firm.js and onward), we
  // can just require() them directly.
  const abs = path.join(REPO_ROOT, relativePath);
  if (!fs.existsSync(abs)) {
    throw new Error(`config missing: ${relativePath}`);
  }
  try {
    // Try direct require first — works if the config has module.exports.
    delete require.cache[require.resolve(abs)];
    const direct = require(abs);
    if (direct && typeof direct === "object" && Object.keys(direct).length > 0) {
      return direct;
    }
  } catch (e) {
    // Fall through to vm-eval path.
  }
  const source = fs.readFileSync(abs, "utf8");
  // Derive the variable name from the file basename — "portfolio.js" =>
  // "portfolio". Append a module.exports assignment so we can pluck it out.
  const constName = path.basename(relativePath, ".js");
  const wrapped = `${source}\n;module.exports = (typeof ${constName} !== 'undefined') ? ${constName} : {};`;
  const vm = require("node:vm");
  const sandbox = { module: { exports: {} }, console };
  sandbox.global = sandbox;
  vm.runInNewContext(wrapped, sandbox);
  return sandbox.module.exports;
}

function readTextConfig(relativePath) {
  const abs = path.join(REPO_ROOT, relativePath);
  if (!fs.existsSync(abs)) return "";
  return fs.readFileSync(abs, "utf8");
}

function readAllConfigs() {
  return {
    firm: readJsConfig("config/firm.js"),
    portfolio: readJsConfig("config/portfolio.js"),
    team: readJsConfig("config/team.js"),
    jobs: readJsConfig("config/jobs.js"),
    brandBrief: readTextConfig("config/brand-brief.md"),
    noFlyList: readTextConfig("config/no-fly-list.md"),
    topicalRubric: readTextConfig("config/topical-rubric.md"),
    weeklyHook: readTextConfig("config/weekly-hook.txt").trim() || null,
  };
}

// ============================================================================
// Topical brief stub (U5 fills in the real fetcher)
// ============================================================================

// Delegates to scripts/cycle/topical-fetcher.js — that module owns the schema,
// the injection-pattern sanitizer, and the fail-soft contract. At cycle runtime,
// Claude Code's Agent tool replaces the `invokeFetcher` callback below with the
// real subagent invocation (using the prompt at scripts/cycle/prompts/topical-
// fetcher.md). For local dry-runs and tests, no invokeFetcher is provided and
// the fetcher gracefully returns an empty brief.
const topicalFetcher = require("./topical-fetcher.js");

async function fetchTopicalBrief(overrides = {}) {
  const brief = await topicalFetcher.fetchTopicalBrief({
    invokeFetcher: overrides.invokeFetcher,
    logger: overrides.logger || ((msg) => console.error(`[cycle] ${msg}`)),
  });
  // run-cycle.js expects { topical, brief, hook } at minimum; the topical-fetcher
  // module returns a richer object — pass it through directly so Author sees
  // source_summary and all_sensitivity_tiers too.
  return brief;
}

// ============================================================================
// Performance log assembly + slicing
// ============================================================================

function slicePerformanceLog(log) {
  // The orchestrator loads max(N) = 12 once and slices per window. The
  // Author prompt then references the slices explicitly.
  return {
    full: log,
    themeDiversity: log.slice(0, THEME_DIVERSITY_N),
    topicalClustering: log.slice(0, TOPICAL_CLUSTERING_N),
    ratingContext: log.slice(0, RATING_CONTEXT_N),
    // For diversity memory specifically — every theme key seen in the
    // window, deduped.
    recentThemeKeys: [
      ...new Set(
        log
          .slice(0, THEME_DIVERSITY_N)
          .flatMap((entry) => (entry.meta && entry.meta.theme_keys) || [])
      ),
    ],
    recentTopicalHooks: log
      .slice(0, TOPICAL_CLUSTERING_N)
      .map((entry) => entry.meta && entry.meta.topical_hook)
      .filter(Boolean),
  };
}

// ============================================================================
// Author and Editor stub functions
//
// These are the seams the cycle.md prompt overrides at runtime. The
// orchestrator's role is to assemble inputs, validate outputs, and route
// retries — not to invoke the API. In production, Claude Code's Agent tool
// produces the structured output that these stub signatures accept.
//
// In --dry-run mode, the Author stub reads a fixture file and returns it
// verbatim; the Editor stub always approves. This lets the team test the
// orchestrator's structural behaviors locally without any API cost.
//
// In tests, these stubs are mocked via dependency injection (see exports
// at the bottom of this file).
// ============================================================================

// Minimal stub for unit tests that pass their own overrides — the real
// fixture is generated dynamically by buildStubFixture() below using the
// live configs, so dry-run can pass smoke gates.
const STUB_AUTHOR_OUTPUT_FIXTURE = {
  site: {
    files: {
      "index.html": [
        "<!doctype html>",
        '<html lang="en">',
        "<head>",
        "  <meta charset=\"utf-8\">",
        "  <title>Root Ventures — stub drop</title>",
        '  <meta name="csp-nonce" content="{{CSP_NONCE}}">',
        "</head>",
        "<body>",
        "  <h1>Root Ventures — stub drop (dry-run)</h1>",
        "  <p>This is a placeholder artifact. The real Author replaces this.</p>",
        "  <a href=\"mailto:hello@root.vc\">hello@root.vc</a>",
        "  <a href=\"/archive/_legacy/\">Past drops</a>",
        '  <script nonce="{{CSP_NONCE}}">console.log("stub");</script>',
        "</body>",
        "</html>",
      ].join("\n"),
    },
  },
  meta: {
    theme_name: "stub-dry-run",
    editorial_note:
      "Dry-run stub artifact for orchestrator structural testing. Not a real drop.",
    where_facts_live: {
      firm_name: "page title",
      mission: "n/a — stub",
      portfolio: "n/a — stub",
      team: "n/a — stub",
      contact: "mailto link in body",
    },
    history_view_concept:
      "A 'Past drops' link in the page body. Stub-level — not in-world.",
    theme_keys: ["stub", "dry-run"],
    topical: false,
    csp_nonce: "{{CSP_NONCE}}",
  },
  social: {
    tweet_draft: "Stub drop for dry-run testing.",
    tweet_thread: [],
    linkedin_draft: "Stub LinkedIn copy for dry-run testing.",
    screenshot_brief: "Screenshot the body of the page. Stub-level — for dry-run only.",
  },
};

// Build a dry-run stub that includes every anchor fact from the live configs,
// so the smoke gate passes. The output is intentionally ugly — it's not a
// "real" drop, just a structural stand-in. Real Authors produce something
// far more interesting; this exists to test orchestrator wiring under
// realistic smoke gates.
function buildStubFixture(configs) {
  const escapeHtml = (s) =>
    String(s)
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;");

  const portfolioEntries = Object.values(configs.portfolio || {})
    .map(
      (p) =>
        `<li><a href="${escapeHtml(p.url || "#")}">${escapeHtml(p.name)}</a> — ${escapeHtml(p.description || "")}</li>`
    )
    .join("\n      ");

  const teamEntries = Object.values(configs.team || {})
    .map(
      (m) =>
        `<li>${escapeHtml(m.name)} — ${escapeHtml(m.title || "")}</li>`
    )
    .join("\n      ");

  const firmName = (configs.firm && configs.firm.name) || "Root Ventures";
  const firmMission =
    (configs.firm && (configs.firm.mission || configs.firm.tagline || configs.firm.thesis)) ||
    "Seeding bold engineers";
  const contact =
    (configs.firm && configs.firm.contact && configs.firm.contact.primary) ||
    "hello@root.vc";

  const html = [
    "<!doctype html>",
    '<html lang="en">',
    "<head>",
    '  <meta charset="utf-8">',
    `  <title>${escapeHtml(firmName)} — dry-run stub</title>`,
    '  <meta name="csp-nonce" content="{{CSP_NONCE}}">',
    "</head>",
    "<body>",
    `  <header><h1>${escapeHtml(firmName)}</h1><p>${escapeHtml(firmMission)}</p></header>`,
    "  <section>",
    "    <h2>Portfolio</h2>",
    "    <ul>",
    `      ${portfolioEntries}`,
    "    </ul>",
    "  </section>",
    "  <section>",
    "    <h2>Team</h2>",
    "    <ul>",
    `      ${teamEntries}`,
    "    </ul>",
    "  </section>",
    `  <footer><a href="mailto:${escapeHtml(contact)}">${escapeHtml(contact)}</a> · <a href="/archive/_legacy/">Past drops</a></footer>`,
    '  <script nonce="{{CSP_NONCE}}">/* dry-run stub */</script>',
    "</body>",
    "</html>",
  ].join("\n");

  return {
    site: { files: { "index.html": html } },
    meta: {
      theme_name: "dry-run-stub",
      editorial_note:
        "Dry-run stub artifact built dynamically from the live configs. The real Author produces something with a conceit. This stub exists only to verify the orchestrator wires inputs through to smoke gates and writes a valid archive.",
      where_facts_live: {
        firm_name: "in <h1>",
        mission: "in <p>",
        portfolio: "<section><h2>Portfolio</h2>",
        team: "<section><h2>Team</h2>",
        contact: "<footer> mailto link",
      },
      history_view_concept:
        "A 'Past drops' link in the footer. Stub-level, not in-world — only here so smoke tests pass.",
      theme_keys: ["dry-run", "stub"],
      topical: false,
      csp_nonce: "{{CSP_NONCE}}",
    },
    social: {
      tweet_draft: "dry-run stub — orchestrator wiring test only.",
      tweet_thread: [],
      linkedin_draft:
        "This is a dry-run stub. The real Author produces a real artifact each Monday.",
      screenshot_brief:
        "No screenshot — this is a dry-run stub, not a real drop.",
    },
  };
}

async function defaultAuthorStub({
  configs,
  performanceLog,
  topicalBrief,
  retryCounter,
  priorCritique,
  fixturePath,
}) {
  // In --fixture-path mode, read the fixture and return it.
  if (fixturePath) {
    const raw = fs.readFileSync(fixturePath, "utf8");
    return JSON.parse(raw);
  }
  // Otherwise: build a stub dynamically from the live configs so the smoke
  // gate passes. The real Author replaces this entire function at runtime
  // via Claude Code's Agent tool.
  if (configs) {
    return buildStubFixture(configs);
  }
  return STUB_AUTHOR_OUTPUT_FIXTURE;
}

async function defaultEditorStub({
  authorOutput,
  configs,
  diversitySlice,
  smokeResult,
}) {
  // Default behavior: approve everything (used by --dry-run, where the goal
  // is to test orchestrator wiring, not Editor logic). Real Editor returns
  // `{ decision, critique, sensitivity_check }` from Claude Code's Agent
  // tool.
  return {
    decision: "approve",
    critique: "Dry-run stub editor: auto-approve.",
    sensitivity_check: authorOutput.meta.topical ? "tier_3" : "non_topical",
  };
}

// ============================================================================
// Smoke gate
//
// Runs the cycle-test suite against the drafted artifact directory and
// the source-scan deny-list. Returns `{ passed: boolean, failures: string[] }`.
// On pass, the orchestrator proceeds to freeze. On fail, the failure list
// is included in the next Author retry's critique.
// ============================================================================

function runSmokeGate(artifactPath) {
  const failures = [];

  // Source-scan first (fast, deterministic, no test runner). Failures here
  // are formatted into a critique the Author can act on directly.
  const scanResult = scanArtifact(artifactPath);
  if (scanResult.violations.length > 0) {
    failures.push(
      ...scanResult.violations.map(
        (v) => `source-scan violation: ${v.file}:${v.line} ${v.label} — ${v.suggestedFix}`
      )
    );
  }

  // Vitest smoke suite. We shell out so vitest's own process boundary
  // applies; this matches `npm run smoke`.
  try {
    execSync(
      `ARTIFACT_PATH=${JSON.stringify(artifactPath)} npx vitest run tests/cycle/`,
      {
        cwd: REPO_ROOT,
        stdio: "pipe",
        encoding: "utf8",
        env: { ...process.env, ARTIFACT_PATH: artifactPath },
      }
    );
  } catch (err) {
    const output = (err.stdout || "") + (err.stderr || "");
    failures.push(
      `smoke-test failure (see output):\n${truncate(output, 4000)}`
    );
  }

  return { passed: failures.length === 0, failures };
}

function truncate(s, n) {
  if (!s) return "";
  if (s.length <= n) return s;
  return s.substring(0, n) + "... [truncated]";
}

// ============================================================================
// Revision loop
// ============================================================================

async function runRevisionLoop({
  configs,
  performanceLog,
  topicalBrief,
  maxRetries,
  authorCall,
  editorCall,
  smokeGateFn,
  freezeFn,
  outputDir,
  cspNonce,
}) {
  const diversity = slicePerformanceLog(performanceLog);
  let attempt = 0;
  let priorCritique = null;
  let lastAuthorOutput = null;
  let lastValidationErrors = null;

  while (attempt <= maxRetries) {
    const retryCounter = attempt;

    // 1. Call Author.
    const authorOutput = await authorCall({
      configs,
      performanceLog,
      topicalBrief,
      retryCounter,
      priorCritique,
      diversity,
    });
    lastAuthorOutput = authorOutput;

    // 2. Validate against schema.
    const validation = validateAuthorOutput(authorOutput);
    lastValidationErrors = validation.errors;
    if (!validation.valid) {
      priorCritique = formatSchemaErrorsAsCritique(validation.errors);
      attempt++;
      continue;
    }

    // 3. Inject the resolved CSP nonce into the meta so freeze can apply it.
    //    Author leaves the placeholder `{{CSP_NONCE}}` in script tags;
    //    freeze substitutes it. meta.csp_nonce gets the resolved value here.
    const finalOutput = {
      ...authorOutput,
      meta: { ...authorOutput.meta, csp_nonce: cspNonce },
    };

    // 4. Freeze to a working directory. This catches Author errors like
    //    "emitted a <script> tag without the nonce placeholder" before
    //    we run the smoke gate.
    let freezeError = null;
    try {
      // Wipe any prior attempt's contents to keep the smoke gate clean.
      if (fs.existsSync(outputDir)) {
        fs.rmSync(outputDir, { recursive: true, force: true });
      }
      fs.mkdirSync(outputDir, { recursive: true });
      freezeFn({ outputDir, authorOutput: finalOutput });
    } catch (err) {
      freezeError = err.message;
    }
    if (freezeError) {
      priorCritique = `freeze-archive rejected the draft: ${freezeError}`;
      attempt++;
      continue;
    }

    // 5. Smoke gate (smoke tests + source scan).
    const smokeResult = smokeGateFn(outputDir);
    if (!smokeResult.passed) {
      priorCritique = formatSmokeFailuresAsCritique(smokeResult.failures);
      attempt++;
      continue;
    }

    // 6. Editor pass.
    const editorDecision = await editorCall({
      authorOutput: finalOutput,
      configs,
      diversitySlice: diversity,
      smokeResult,
    });

    if (editorDecision.decision === "approve") {
      return {
        success: true,
        authorOutput: finalOutput,
        editorDecision,
        smokeResult,
        retriesUsed: attempt,
      };
    }

    // 7. Editor rejected — retry.
    priorCritique = formatEditorRejectAsCritique(editorDecision);
    attempt++;
  }

  // Loop exhausted.
  return {
    success: false,
    failureReason: `Revision loop exhausted after ${attempt} attempts. Last critique: ${truncate(
      priorCritique || "(none)",
      1000
    )}`,
    retriesUsed: attempt,
    lastAuthorOutput,
    lastValidationErrors,
  };
}

function formatSchemaErrorsAsCritique(errors) {
  return [
    "Your output did not match the required schema. Fix each error and try again:",
    ...errors.map((e) => `  - ${e}`),
    "",
    "Refer to scripts/cycle/output-schema.js for the exact shape.",
  ].join("\n");
}

function formatSmokeFailuresAsCritique(failures) {
  return [
    "Smoke tests rejected the draft. Address each failure on retry:",
    ...failures.map((f) => `  - ${f}`),
  ].join("\n");
}

function formatEditorRejectAsCritique(editorDecision) {
  return [
    "The Editor rejected the draft. Their critique:",
    editorDecision.critique || "(no critique provided)",
    editorDecision.sensitivity_check
      ? `Sensitivity check: ${editorDecision.sensitivity_check}`
      : "",
  ]
    .filter(Boolean)
    .join("\n");
}

// ============================================================================
// Main entry
// ============================================================================

async function main(rawArgv = process.argv.slice(2), overrides = {}) {
  let opts;
  try {
    opts = parseCliArgs(rawArgv);
  } catch (err) {
    process.stderr.write(`run-cycle: ${err.message}\n`);
    return 4;
  }

  const cycleDate = opts.artifactDate || todayUtcIso();
  if (!isValidDateString(cycleDate)) {
    process.stderr.write(`run-cycle: invalid --artifact-date: ${cycleDate}\n`);
    return 4;
  }

  let configs;
  try {
    configs = overrides.configs || readAllConfigs();
  } catch (err) {
    process.stderr.write(`run-cycle: config read failed: ${err.message}\n`);
    return 4;
  }

  const archiveRoot = path.join(REPO_ROOT, "archive");
  const performanceLog = overrides.performanceLog || assemblePerformanceLog(archiveRoot);
  const topicalBrief = overrides.topicalBrief || (await (overrides.topicalFn || fetchTopicalBrief)());

  // Output dir: dry-run uses /tmp/; real runs use archive/YYYY-MM-DD/.
  const outputDir = overrides.outputDir
    || (opts.dryRun
      ? path.join("/tmp", `cycle-dryrun-${cycleDate}-${process.pid}`)
      : path.join(archiveRoot, cycleDate));

  // Per-run CSP nonce.
  const cspNonce = overrides.cspNonce || generateCspNonce();

  // Stub callables — overridable for tests.
  const authorCall = overrides.authorCall
    || ((input) => defaultAuthorStub({
      ...input,
      fixturePath: opts.fixturePath || (opts.dryRun ? null : null),
    }));
  const editorCall = overrides.editorCall || defaultEditorStub;
  const smokeGateFn = overrides.smokeGateFn || runSmokeGate;
  const freezeFn = overrides.freezeFn || freeze;

  const loopResult = await runRevisionLoop({
    configs,
    performanceLog,
    topicalBrief,
    maxRetries: opts.maxRetries,
    authorCall,
    editorCall,
    smokeGateFn,
    freezeFn,
    outputDir,
    cspNonce,
  });

  if (!loopResult.success) {
    const summary = {
      success: false,
      cycle_date: cycleDate,
      output_dir: null,
      theme_name: null,
      topical: null,
      retries_used: loopResult.retriesUsed,
      max_retries: opts.maxRetries,
      failure_reason: loopResult.failureReason,
      dry_run: opts.dryRun,
      max_turns: MAX_TURNS,
      max_run_minutes: MAX_RUN_MINUTES,
    };
    // Clean up any partially-written draft.
    if (fs.existsSync(outputDir) && opts.dryRun) {
      fs.rmSync(outputDir, { recursive: true, force: true });
    }
    process.stdout.write(JSON.stringify(summary) + "\n");
    // Distinguish exit codes per the file header.
    if (loopResult.lastValidationErrors && loopResult.lastValidationErrors.length > 0) {
      return 2;
    }
    return 3;
  }

  // Success — archive directory is already written by the freeze step
  // inside the revision loop. In dry-run, leave the temp directory for
  // inspection.
  const summary = {
    success: true,
    cycle_date: cycleDate,
    output_dir: outputDir,
    artifact_path: outputDir,
    theme_name: loopResult.authorOutput.meta.theme_name,
    topical: !!loopResult.authorOutput.meta.topical,
    topical_hook: loopResult.authorOutput.meta.topical_hook || null,
    retries_used: loopResult.retriesUsed,
    max_retries: opts.maxRetries,
    dry_run: opts.dryRun,
    max_turns: MAX_TURNS,
    max_run_minutes: MAX_RUN_MINUTES,
    press_kit: {
      tweet_draft: loopResult.authorOutput.social.tweet_draft,
      screenshot_brief: loopResult.authorOutput.social.screenshot_brief,
    },
    files_written: fs.existsSync(outputDir)
      ? fs.readdirSync(outputDir).sort()
      : [],
  };

  // Stage files but DO NOT commit/push (U6 workflow handles git ops).
  // Production runs perform `git add` separately; tests don't need it.
  if (!opts.dryRun && !overrides.skipStage) {
    try {
      stageArchive(outputDir);
    } catch (err) {
      // Staging failure is non-fatal — surface it but mark success.
      summary.stage_warning = err.message;
    }
  }

  process.stdout.write(JSON.stringify(summary) + "\n");
  return 0;
}

function stageArchive(outputDir) {
  // We use the git CLI directly so this matches what a developer would do.
  // No commit, no push — just stage.
  const rel = path.relative(REPO_ROOT, outputDir);
  execSync(`git add ${JSON.stringify(rel)}`, { cwd: REPO_ROOT, stdio: "pipe" });
}

// ============================================================================
// Exports — for tests and for the cycle.md prompt's spawn-the-orchestrator
// step.
// ============================================================================

module.exports = {
  main,
  parseCliArgs,
  slicePerformanceLog,
  readAllConfigs,
  runRevisionLoop,
  formatSchemaErrorsAsCritique,
  formatSmokeFailuresAsCritique,
  formatEditorRejectAsCritique,
  generateCspNonce,
  todayUtcIso,
  STUB_AUTHOR_OUTPUT_FIXTURE,
  buildStubFixture,
  PR_BODY_TEMPLATE,
  SUCCESS_ISSUE_TEMPLATE,
  FAILURE_ISSUE_TEMPLATE,
  renderTemplate,
  THEME_DIVERSITY_N,
  TOPICAL_CLUSTERING_N,
  RATING_CONTEXT_N,
  MAX_TURNS,
  MAX_RUN_MINUTES,
  DEFAULT_MAX_RETRIES,
};

// CLI invocation — runs main() when this file is executed via `node`.
if (require.main === module) {
  main()
    .then((code) => process.exit(code))
    .catch((err) => {
      process.stderr.write(`run-cycle: ${err.stack || err.message}\n`);
      process.exit(1);
    });
}
